#!/bin/bash

mkdir -p /home/jovyan/.jupyter/lab/user-settings/@jupyterlab/toc-extension
cp ./.user-settings/@jupyterlab/toc-extension/plugin.jupyterlab-settings /home/jovyan/.jupyter/lab/user-settings/@jupyterlab/toc-extension/plugin.jupyterlab-settings